config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "static_pages#home"
  resources :play, only: :show do
    post "guess", on: :member
    resources :scores, only: [:index, :new, :create]
  end
  resources :scores, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character_location.rb
class CharacterLocation < ApplicationRecord
  belongs_to :scene
end

app/models/scene.rb
class Scene < ApplicationRecord
  has_many :character_locations, dependent: :destroy
  has_many :scores, dependent: :destroy
end

app/models/score.rb
require "swearjar"

class Score < ApplicationRecord
  belongs_to :scene
  validates :player_name, presence: true,
                          length: { minimum: 1, maximum: 140 }
  validates :time, presence: true
  
  validate :player_name_cant_contain_bad_language

  private

    def player_name_cant_contain_bad_language
      sj = Swearjar.default
      if sj.profane?(player_name)
        errors.add(:player_name, "Please refrain from using bad language.")
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/play_controller.rb
class PlayController < ApplicationController
  def show
    @scene = Scene.find(params[:id])
    session[:game_data] = {
      "scene" => @scene.id,
      "found" => @scene.character_locations.inject({}) { |acc, char_loc| acc[char_loc.character] = false; acc },
      "start_time" => Time.now
    }
  end

  def guess
    game_data = session[:game_data]
    scene = Scene.find(game_data["scene"])

    char_loc = scene.character_locations.find_by(character: params[:character])
    hit = char_loc && correct_guess?(char_loc.x, char_loc.y, params[:x].to_i, params[:y].to_i)

    game_data["found"][params[:character]] = hit
    remaining = game_data["found"].select { |k, v| !v }.keys

    if remaining.empty?
      game_data["end_time"] = Time.now
      game_data["won"] = true
    end

    session[:game_data] = game_data

    respond_to do |format|
      format.json do
        output = {}
        output[:result] = hit ? "hit" : "miss"
        output[:remaining] = remaining unless remaining.empty?
        if remaining.empty?
          output[:won] = true 
          output[:time] = (game_data["end_time"] - Time.parse(game_data["start_time"])).round
        end
        render json: output
      end
    end
  end

  private

    def correct_guess?(x1, y1, x2, y2)
      Math.sqrt((x1 - x2)**2 + (y1 - y2)**2) < 30 # 30 pixels radius
    end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  PER_PAGE = 30

  def index
    @scene = Scene.find(params[:play_id])
    page = (params[:page] || 1).to_i
    per_page = PER_PAGE
    @scores = @scene.scores.order(time: :ASC, created_at: :ASC, id: :ASC).limit(per_page).offset((page - 1) * per_page)
    total_scores = @scene.scores.count
    @pagination = {
      page: page,
      per_page: per_page,
      pages: total_scores / per_page + 1
    }
  end

  def create
    scene_id = params[:play_id].to_i

    if scene_id != session[:game_data]["scene"]
      head :bad_request and return
    end

    unless session[:game_data]["won"]
      redirect_to play_path(scene_id) and return
    end

    @scene = Scene.find(scene_id)
    end_time = Time.parse(session[:game_data]["end_time"])
    start_time = Time.parse(session[:game_data]["start_time"])
    @score = @scene.scores.build(player_name: params[:player_name], time: (end_time - start_time).round)
    if @score.save
      session[:game_data] = nil # clear
      redirect_to score_url(@score)
    else
      render :new
    end
  end

  def show
    score = Score.find(params[:id])
    count_so_far = Score.where("time < :game_time", {game_time: score.time})
                        .or(Score.where("time = :game_time AND created_at < :at_stamp",
                                          {game_time: score.time, at_stamp: score.created_at}))
                        .or(Score.where("time = :game_time AND created_at = :at_stamp AND id <= :id",
                                          {game_time: score.time, at_stamp: score.created_at, id: score.id}))
                        .count
    redirect_to play_scores_url(score.scene, page: count_so_far / PER_PAGE + 1, anchor: score.id)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @scenes = Scene.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/play_helper.rb
module PlayHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
  def format_time(time)
    if time < 60
      "00:#{"%02d" % time}"
    else
      arr = []
      until time == 0
        arr << time % 60
        time /= 60
      end
      arr.reverse
          .map { |n| "%02d" % n }
          .join(":")
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Where's Waldo?</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
      <footer><span>"Where's Waldo?" by Martin Handford. Programming by <a href="https://github.com/themetar">themetar</a>.</span></footer>
    </div>
  </body>
</html>

app/views/play/show.html.erb
<h1 class="scene-title">
  <span>
    <%= @scene.title %> | 
    <%= image_tag "logo.png" %> |
    <small>Find Odlaw, Wizard Whitebeard, Wenda, and Waldo</small>
  </span>
</h1>
<div class="fullscreen-overlay hidden">
  <%= render "shared/score_form" %>
</div>
<div id="scene-container">
  <%= image_tag "scenes/#{@scene.asset_name}" %>
</div>

app/views/scores/_pagination.html.erb
<div class="center">
  <ul class="pagination">
    <li>
      <%= link_to "Previous",
                  (@pagination[:page] > 1 ? "?page=#{@pagination[:page] - 1}" : ""),
                  @pagination[:page] < 2 ? {class: "inactive"} : {} %>
    </li>
    <% @pagination[:pages].times do |n| %>
    <li>
      <%= link_to n + 1,
                  @pagination[:page] == n + 1 ? "" : "?page=#{n + 1}",
                  @pagination[:page] == n + 1 ? {class: "current"} : {} %>
    </li>
    <% end %>
    <li>
      <%= link_to "Next",
                  (@pagination[:page] < @pagination[:pages] ? "?page=#{@pagination[:page] + 1}" : ""),
                  @pagination[:page] > @pagination[:pages] - 1 ? {class: "inactive"} : {} %>
    </li>
  </ul>
</div>

app/views/scores/_score.html.erb
<span class="name"><%= score.player_name %></span>
<span class="time"><%= format_time(score.time) %></span>

app/views/scores/index.html.erb
<div class="to-home center">
  <a href="<%= root_path %>">
    <%= image_tag "logo.png" %>
    <div>Where's Waldo?</div>
  </a>
</div>
<h1>High scores for "<%= link_to @scene.title, play_path(@scene) %>"</h1>
<% if @pagination[:pages] > 1 %> 
<%= render "pagination" %>
<% end %> 
<ol start="<%= (@pagination[:page] - 1) * @pagination[:per_page] + 1 %>" class="scoreboard">
<% @scores.each_with_index do |score, i| %>
  <li id="<%= score.id %>">
    <span class="rank"><%= (@pagination[:page] - 1) * @pagination[:per_page] + i + 1 %></span>
    <%= render "score", score: score %>
  </li>
<% end %>
</ol>
<% if @pagination[:pages] > 1 %> 
<%= render "pagination" %>
<% end %> 

app/views/scores/new.html.erb
<%= render 'shared/score_form' %>

app/views/shared/_score_form.html.erb
<section class="score-form">
  <h2 class="center">Congratulations, you found everyone!</h2>
  <p class="center">Add your achievement to the scoreboard.</p>
  <%= form_with url: play_scores_path(@scene), method: "post", local: true do %>
    <div class="sections">
      <div>
        <%= label_tag :player_name, "Your name" %>
        <%= text_field_tag :player_name, @score ? @score.player_name : "" %>
        <% if @score && @score.errors.any? %>
        <div>
        <% @score.errors[:player_name].each do |error_msg| %>
          <p class="form-error"><%= error_msg.capitalize %></p>
        <% end %>
        </div>
        <% end %>
      </div>
      <div>
        <span>Time</span>
        <span class="time"><%= if @score then format_time(@score.time) end %></span>
      </div>
    </div>
    <div class="center">
      <%= submit_tag "Add" %>
    </div>
  <% end %>
</section>

app/views/static_pages/home.html.erb
<div class="home center">
  <header class="game-info">
    <p>Find Odlaw, Wizard Whitebeard, Wenda, and Waldo</p>
    <%= image_tag "logo.png" %>
    <h1>Where's Waldo?</h1>
  </header>
  <button>Play</button>
  <ol class="scenes-list hidden">
    <p>Select a page:</p>
    <% @scenes.each do |scene| %>
    <li><%= link_to scene.title, play_path(scene) %></li>
    <% end %>
  </ol>
</div>